### ISSUE TITLE
Readiness endpoint could check if upload was successful

### ISSUE THREAD

**Issue by agazso** [ethersphere/gateway-proxy#302]
On the public gateway there is an issue with the Bee nodes that may cause the nodes being full and therefore failing to upload data to them (see https://github.com/ethersphere/bee/issues/3194).

It would be good if the `/health` endpoint would try to upload a single chunk worth of random data to check if this is the case and if the upload fails then return an error, so that it can be removed from the load balancer.

**Comment by agazso** [comment]
> Good idea just please use `/readiness` endpoint for it there is already some check under it
> https://github.com/ethersphere/gateway-proxy/blob/master/src/server.ts#L78

Thanks, changed the title accordingly.

**Comment by Cafe137** [comment]
Should we use deferred or direct upload for the single chunk?

**Comment by agazso** [comment]
Deferred, because the goal is just to check if the node works correctly, not the network itself.
