### ISSUE TITLE
Reupload pinned content periodically

### ISSUE THREAD

**Issue by agazso** [ethersphere/gateway-proxy#309]
So that the content is available for other nodes on the network. It can be done using the `/stewardship` [endpoint](https://docs.ethswarm.org/api/#tag/Stewardship/paths/~1stewardship~1%7Breference%7D/put), by using the hashes from the list of [pinned nodes](https://docs.ethswarm.org/api/#tag/Pinning/paths/~1pins/get).

There could be a new environment variable (`REUPLOAD_PERIOD`) which would define the time when the reupload would happen.

**Comment by luissanchez0305** [comment]
@agazso does this feature is exclusive from the others in gateway-proxy, same as extended and autobuy?

**Comment by agazso** [comment]
This is independent of other features. If the `REUPLOAD_PERIOD` is not undefined then this should happen every `REUPLOAD_PERIOD` seconds.

**Comment by luissanchez0305** [comment]
@agazso I already have all the logic to retrieve all the pinned content according to the gateway procedures. Now I lack the criteria to know when to reupload the content. I tried using `.isReferenceRetrievable()` method but I'm always getting `true`
What other criteria should I use to know when to reupload?
Also, I found the `.reuploadPinnedData()` to finish the job, so I think half the battle has been done already

**Comment by agazso** [comment]
Yes, it's the `.isReferenceRetrievable()` method. If it returns true, then there is nothing to do, because the data can be found on the network (at least from the perspective of the Bee node).

If it returns `false` then it should call the `.reuploadPinnedData()`.
