### ISSUE TITLE
Uploading long filenames fails

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/gateway-proxy#312]
Uploading a file named 

digital_innovation_hubs_in_digital_europe_programme_25-01-2021_v23_C35B39CC-C9A7-25BE-09DFD0C05A10616F_70324.pdf

fails with a

![image](https://user-images.githubusercontent.com/1554520/187252839-adfdd0fd-b131-4b0b-b87c-79b530fb25d0.png)

Supposedly because of a too-long filename.

Successfully uploaded version with shortened filename: 
https://gateway.fairdatasociety.org/access/a00131ef99a9ea3d6d8fdf184f6e8b67daea1bc20b119bea0f40c80d2c7d013d

Expected behavior:
- ideally, filename length should not be a limitation for uploads,
- at a minimum, the frontend should return the reason for failure and what lenght filenames are supported.

**Comment by agazso** [comment]
Tracking this issue at the `gateway-ui` repo because this is an issue with the UI, not the proxy service itself.

https://github.com/ethersphere/gateway-ui/issues/308

Closing this issue here.
