### ISSUE TITLE
Readiness endpoint could return error when there is no available postage stamp

### ISSUE THREAD

**Issue by agazso** [ethersphere/gateway-proxy#338]
Currently the `/readiness` endpoint returns `200 OK` even when there is no available valid postage stamp. Therefore the loadbalancer may select the proxy to forward requests and they may fail.

It would be better if the `/readiness` endpoint would return an error so that the loadbalancer could remove it.

**Comment by AuHau** [comment]
Currently, `/readiness` is just simply proxied from Bee: https://github.com/ethersphere/gateway-proxy/blob/master/src/server.ts#L90

Although I am not sure why it proxies to `/` path instead of Bee's `/readiness`.

**Comment by Cafe137** [comment]
This PR will improve readiness check: https://github.com/ethersphere/gateway-proxy/pull/327
I think this issue is for improving on this approach even further.

**Comment by Cafe137** [comment]
Since we are about to tie the readiness check to uploading a chunk, that transitively checks for stamp availability as well, so I am linking that PR here
