### ISSUE TITLE
Autobuy will try to buy new stamps even if valid stamps exists when proxy is restarted 

### ISSUE THREAD

**Issue by darkobas2** [ethersphere/gateway-proxy#386]
test: have valid stamps
restart proxy or bee or both.

it will try buy new stamp

**Comment by Cafe137** [comment]
Thanks for the report!

The proxy only considers stamps valid when they have the same depth and amount as configured through the env vars. So an existing stamp may be ignored on purpose, even if it is beefier or has less capacity. Maybe this is the case?
