### ISSUE TITLE
readiness check causes split failed errors

### ISSUE THREAD

**Issue by darkobas2** [ethersphere/gateway-proxy#469]
the readiness chunk upload seems to cause "level"="error" "logger"="node/api/post_chunk" "msg"="done split failed" errors on bee.

the error then causes gateway proxy not be healthy.

I have disabled the chunk upload test in gateway proxy  and at the same time started to upload periodically chunks to every neighborhood (via gateway proxy) and I had not seen this error occur on bee (yet... been almost 12 hours)

I dont know what the bee error means. but its not good on gateway proxy side as it thinks bee is not healthy

**Comment by Cafe137** [comment]
It is now opt-in with READINESS_CHECK=true
